App class and scenes
sjtolley9/fruitcake-frog pull request #6
Opened 2022-01-19 20:02 UTC by MisterBlue1369

implement of app class to separe it from main function

and implement scene class for the gameplay scene and later use it for menus, etc

2022-01-19 20:40 UTC, sjtolley9 reviewed
There's a couple changes requested to improve the design, but overall the structure looks really good!

2022-01-19 20:40 UTC, sjtolley9 commented on headers/Scene.hpp
> +		virtual void OnUpdate() = 0;
We'll want to pass `elapsedTime` to the update method so updates are based on time and not frames.
```suggestion
		virtual void OnUpdate(Uint32 elapsedTime) = 0;
```

2022-01-19 20:40 UTC, sjtolley9 commented on headers/Application.hpp
> +		void run();
We should include methods to push/pop methods from the Scene stack, allowing gameplay to be passed to other scenes. Make sure we update `currentScene` when we do this.

2022-01-20 00:44 UTC, MisterBlue1369 commented
i think is done

2022-01-20 02:05 UTC, sjtolley9 requested changes

2022-01-20 02:05 UTC, sjtolley9 commented on headers/Scene.hpp
> +		virtual void OnUpdate(uint32_t elapsedTime) = 0;
This should use the `Uint32` type from `"SDL.h"` so as to keep types consistent throughout.

2022-01-20 02:05 UTC, sjtolley9 commented on src/Application.cpp
> +}
I'm not sure we need this method. Push and pop should be enough. Plus relying on `sceneIndex` for changing could lead to unexpected results, see next comment. Removing this and the `removeScene` will allow the scene container to better reflect a stack.

2022-01-20 02:05 UTC, sjtolley9 commented on src/Application.cpp
> +}
As I mentioned, using a `sceneIndex` to change or remove scenes could result in weird behavior that would be difficult to debug. An example of this being that if we were to remove a scene, the scene index for all scenes placed on the stack after that scene will decrease by one.

2022-01-20 02:09 UTC, sjtolley9 commented
### An important note:
After this Pull Request gets merged, I'm going to be adding in a few new things and won't be merging in pull requests unless they directly address an existing issue.

2022-01-20 02:32 UTC, MisterBlue1369 commented
now i think is ready?

2022-01-20 04:13 UTC, sjtolley9 reviewed
Looks good, I'll do a quick compile check and merge it in.

2022-01-20 04:43 UTC, sjtolley9 approved these changes

2022-01-20 04:43 UTC, merged